# Generated by Django 5.2.3 on 2025-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regla",
            name="peso",
            field=models.IntegerField(
                default=1, help_text="Peso o importancia de la regla"
            ),
        ),
    ]
