# Generated by Django 5.2.3 on 2025-06-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_regla_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regla',
            name='peso',
            field=models.PositiveSmallIntegerField(default=1, help_text='Peso o importancia de la regla'),
        ),
    ]
