# Generated by Django 5.2.3 on 2025-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_regla_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='explicacion_humana',
            field=models.TextField(blank=True, help_text='Explicación amigable para el usuario', null=True),
        ),
    ]
