# Generated by Django 5.2.3 on 2025-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0004_regla_explicacion_humana"),
    ]

    operations = [
        migrations.AddField(
            model_name="hecho",
            name="pregunta",
            field=models.CharField(default="Pregunta no especificada", max_length=255),
            preserve_default=False,
        ),
    ]
