# Generated by Django 5.2.3 on 2025-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0005_hecho_pregunta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regla",
            name="condicion",
        ),
        migrations.AddField(
            model_name="regla",
            name="hecho",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="regla",
            name="conclusion",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="regla",
            name="peso",
            field=models.IntegerField(default=1),
        ),
    ]
